version: '3'
services:
  shell:
    build:
      context: .
      dockerfile: Dockerfile.nobinder
    image: flexvalue_shell
    stdin_open: true
    tty: true
    entrypoint: /bin/sh
    volumes:
      - .:/app
      - /app/tests/__pycache__/
      - $HOME/.config:/root/.config

  flexvalue:
    image: flexvalue_shell
    entrypoint: flexvalue
    volumes:
      - .:/app
      - /app/tests/__pycache__/
      - $HOME/.config:/root/.config

  docs:
    image: flexvalue_shell
    ports:
      - "${HOST_PORT_DOCS:-8000}:8000"
    entrypoint: make -C docs livehtml
    volumes:
      - .:/app
      - /app/tests/__pycache__/

  test:
    image: flexvalue_shell
    entrypoint: py.test -n0
    volumes:
      - .:/app
      - /app/tests/__pycache__/
      - $HOME/.config:/root/.config

  jupyter:
    image: flexvalue_shell
    ports:
      - "${HOST_PORT_JUPYTER:-8888}:${HOST_PORT_JUPYTER:-8888}"
    entrypoint: |
      jupyter lab notebooks/ --ip=0.0.0.0 --port=${HOST_PORT_JUPYTER:-8888} --allow-root --no-browser
    volumes:
      - .:/app
      - /app/tests/__pycache__/

  postgresql:
    image: postgres:15.1
    restart: always
    shm_size: 4g
    environment:
      - POSTGRES_PASSWORD=example
    ports:
      - 5432:5432
